### ISSUE TITLE
A ValueError

### ISSUE THREAD

**Issue by ghost** [giancds/attentive_lm#1]
We followed your config: Python 3 + Tensorflow 1.4, But we got a ValueError after the process of training .
Traceback (most recent call last):
  File "train_attentive_lm.py", line 346, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_attentive_lm.py", line 342, in main
    train_lm()
  File "train_attentive_lm.py", line 267, in train_lm
    keep_attention_weights=True)
  File "/home/jingkun/attentive_lm-master/attentive_lm.py", line 87, in __init__
    seq_lengths=seq_lengths, keep_attention_weights=keep_attention_weights)
  File "/home/jingkun/attentive_lm-master/attentive_lm.py", line 213, in attentive_lm
    skip_conditionals=True)
  File "/home/jingkun/attentive_lm-master/rnn.py", line 272, in rnn_step
    new_output, new_state = call_cell()
  File "/home/jingkun/attentive_lm-master/attentive_lm.py", line 211, in <lambda>
    call_cell=lambda: cell(input_, final_state),  # pylint: disable=W0640
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1066, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 438, in call
    self._linear = _Linear([inputs, h], 4 * self._num_units, True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1171, in __init__
    initializer=kernel_initializer)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 1203, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 1092, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 417, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 1583, in wrapped_custom_getter
    *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 186, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 186, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 760, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable Model/attentive_lm/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

**Comment by sunnydaystar** [comment]
I came across the same error when testing this code, made a change in utils.py, near line 84 and it is working now.
old: 
lstm_cell0 = tf.contrib.rnn.BasicLSTMCell(
      size, forget_bias=1.0, reuse=not is_training)
new: 
lstm_cell0 = tf.contrib.rnn.BasicLSTMCell(
      size, forget_bias=1.0, reuse=tf.get_variable_scope().reuse)
